### ISSUE TITLE
Crash on Server Startup

### ISSUE THREAD

**Issue by alanassis** [loleq2105/Ag4tr#1]
[2020-12-07-2.log](https://github.com/loleq2105/Ag4tr/files/5650858/2020-12-07-2.log)

**Comment by loleq2105** [comment]
I apparently put the energy tooltip initialization method into the wrong class. This is changed (011b5ef774eab39149b8ca5be92207f982d440ec) in the latest release, let me know if this fixes the issue.

**Comment by alanassis** [comment]
Yes, that solved it. Thanks!
