### ISSUE TITLE
crashed due to issue GEAREBORN

### ISSUE THREAD

**Issue by Eldoradoge** [loleq2105/Ag4tr#11]
hi im getting a crash due to what i believe is gearreborn being outdated compared to techreborn and reborncore

**Comment by loleq2105** [comment]
I was expecting this due to TR still being in beta. I'd appreciate a crash log regardless, to see exactly what catastrophic change has been made.

**Comment by Eldoradoge** [comment]
[crash-2022-04-24_12.48.18-client.txt](https://github.com/loleq2105/GearReborn/files/8549186/crash-2022-04-24_12.48.18-client.txt)

**Comment by loleq2105** [comment]
fixed in the latest release
