### ISSUE TITLE
[Windows Defender False Virus] Detecting GearReborn as Virus

### ISSUE THREAD

**Issue by itsdinkd** [loleq2105/Ag4tr#14]
https://github.com/ShetiPhian/Localizations-and-Issues/issues/349

As mentioned to ShetiPhian, people who are downloading my modpack "Another Quality Modpack 2" are getting false negatives of viruses due to Windows Defender sucking ass. They download from CF, and if they have windows defender, 9/10 several mods are getting quarantined. This is preventing them from playing the pack (Not blaming you)

I wanted to give you a heads up, as ShetiPhian also suggested. I will be reporting to the other mods that were falsely identified as a virus. I had roughly over 10 people that complained about this today in our discord and they all downloaded the pack from CF. 

![image](https://user-images.githubusercontent.com/35115304/166414505-bc95e9c5-2e4f-4542-8787-bd800a765b4d.png)

**Comment by ShetiPhian** [comment]
I've gotten the all clear from Microsoft Security Intelligence 
Figuring out how was a bit annoying and was rejected at first, so here is what worked.
[It will take a while to clear your file, as we are low priority]

Verify the false positive with Kaspersky (https://opentip.kaspersky.com)

Next go to: https://www.microsoft.com/en-us/wdsi/filesubmission
Choose Software developer and continue
Security product is Microsoft Defender Antivirus
Type anything you want into Company Name
"No" to Microsoft support case number
Skip Software Assurance ID, its for enterprise clients
"No — remove the file automatically after a period of inactivity"
What do you believe this file is? = Incorrectly detected as malware/malicious
Detection name = Trojan:Script/Wacatac.B!ml

**Comment by loleq2105** [comment]
Done <3
