### ISSUE TITLE
The game crashes when the stun gun is in the inventory

### ISSUE THREAD

**Issue by Pandorum301** [loleq2105/Ag4tr#15]
If the stun gun gets into the player's inventory (picked it up from the ground or moved it to the inventory using the cursor), the game will crash.
[crash-2022-11-25_21.32.19-server.txt](https://github.com/loleq2105/GearReborn/files/10094657/crash-2022-11-25_21.32.19-server.txt)

**Comment by loleq2105** [comment]
Apologies for neglecting bugs for such long periods, in spite of this project's small size. I will get on this asap. Access to a decent pc is still difficult for me, but this should change soon enough.
