### ISSUE TITLE
Crashing when turning on Night Vision Goggles

### ISSUE THREAD

**Issue by xErrorAmelie** [loleq2105/Ag4tr#16]
Mod Version: 1.19-0.1.15
MC Version: 1.19.2

When I turn on NVG my client crashes and I can't join back the server. 
This also happend to other people who tried the NVG.

Crashlog: https://mclo.gs/ahfKmxD

**Comment by loleq2105** [comment]
Duplicate of #15, maybe eventually I'll go about making some update releases for past MC versions just to feel better abt myself
