### ISSUE TITLE
NVG corrupts server player data

### ISSUE THREAD

**Issue by windowslogic** [loleq2105/Ag4tr#6]
When attempting to put on NVG, the server kicks you and says, "Internal Server Error". This does not happen in single player, only multiplayer. You can no longer log into a server after putting on NVG.

Here's the server log:
`12.08 22:13:11 [Connect] User WindowsLogic, IP 193.56.252.19
12.08 22:13:11 [Server] Server thread/WARN Player class_3222['WindowsLogic'/576426, l='ServerLevel[world_test]', x=-19981.79, y=12.00, z=-2129.17] could not be synced because server networking isn't set up yet.
12.08 22:13:11 [Server] Server thread/INFO WindowsLogic joined the game
12.08 22:13:11 [Server] Server thread/INFO WindowsLogic uses DualWielding Mod
12.08 22:13:11 [Server] Server thread/WARN Failed to handle packet for /193.56.252.19:50293
12.08 22:13:11 [Server] INFO net.minecraft.class_148: Ticking player
12.08 22:13:11 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:530) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
12.08 22:13:11 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class dev.loleq21.gearreborn.GearRebornClient in environment type SERVER
12.08 22:13:11 [Server] INFO at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:78) ~[fabric_1.17.1.jar:?]
12.08 22:13:11 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:191) ~[fabric_1.17.1.jar:?]
12.08 22:13:11 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:156) ~[fabric_1.17.1.jar:?]
12.08 22:13:11 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric_1.17.1.jar:?]
12.08 22:13:11 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
12.08 22:13:11 [Server] INFO at dev.loleq21.gearreborn.NightvisionGoggles.method_7888(NightvisionGoggles.java:66) ~[GearReborn-1.17-0.1.8.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_1799.method_7917(class_1799.java:520) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_1661.method_7381(class_1661.java:262) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-server.jar:?]
12.08 22:13:11 [Server] INFO ... 9 more
12.08 22:13:11 [Multicraft] WindowsLogic ran command Message of the Day
12.08 22:13:12 [Server] Server thread/WARN Failed to handle packet for /193.56.252.19:50293
12.08 22:13:12 [Server] INFO net.minecraft.class_148: Ticking player
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:530) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
12.08 22:13:12 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class dev.loleq21.gearreborn.GearRebornClient in environment type SERVER
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:78) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:191) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:156) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
12.08 22:13:12 [Server] INFO at dev.loleq21.gearreborn.NightvisionGoggles.method_7888(NightvisionGoggles.java:66) ~[GearReborn-1.17-0.1.8.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1799.method_7917(class_1799.java:520) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1661.method_7381(class_1661.java:262) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO ... 9 more
12.08 22:13:12 [Server] Server thread/WARN Failed to handle packet for /193.56.252.19:50293
12.08 22:13:12 [Server] INFO net.minecraft.class_148: Ticking player
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:530) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
12.08 22:13:12 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class dev.loleq21.gearreborn.GearRebornClient in environment type SERVER
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:78) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:191) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:156) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
12.08 22:13:12 [Server] INFO at dev.loleq21.gearreborn.NightvisionGoggles.method_7888(NightvisionGoggles.java:66) ~[GearReborn-1.17-0.1.8.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1799.method_7917(class_1799.java:520) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1661.method_7381(class_1661.java:262) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO ... 9 more
12.08 22:13:12 [Server] Server thread/WARN Failed to handle packet for /193.56.252.19:50293
12.08 22:13:12 [Server] INFO net.minecraft.class_148: Ticking player
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:530) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
12.08 22:13:12 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class dev.loleq21.gearreborn.GearRebornClient in environment type SERVER
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:78) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:191) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:156) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
12.08 22:13:12 [Server] INFO at dev.loleq21.gearreborn.NightvisionGoggles.method_7888(NightvisionGoggles.java:66) ~[GearReborn-1.17-0.1.8.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1799.method_7917(class_1799.java:520) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1661.method_7381(class_1661.java:262) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO ... 9 more
12.08 22:13:12 [Server] Server thread/WARN Failed to handle packet for /193.56.252.19:50293
12.08 22:13:12 [Server] INFO net.minecraft.class_148: Ticking player
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:530) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
12.08 22:13:12 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class dev.loleq21.gearreborn.GearRebornClient in environment type SERVER
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:78) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:191) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:156) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
12.08 22:13:12 [Server] INFO at dev.loleq21.gearreborn.NightvisionGoggles.method_7888(NightvisionGoggles.java:66) ~[GearReborn-1.17-0.1.8.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1799.method_7917(class_1799.java:520) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1661.method_7381(class_1661.java:262) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO ... 9 more
12.08 22:13:12 [Server] Server thread/WARN Failed to handle packet for /193.56.252.19:50293
12.08 22:13:12 [Server] INFO net.minecraft.class_148: Ticking player
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:530) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:212) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
12.08 22:13:12 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class dev.loleq21.gearreborn.GearRebornClient in environment type SERVER
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:78) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:191) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:156) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric_1.17.1.jar:?]
12.08 22:13:12 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
12.08 22:13:12 [Server] INFO at dev.loleq21.gearreborn.NightvisionGoggles.method_7888(NightvisionGoggles.java:66) ~[GearReborn-1.17-0.1.8.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1799.method_7917(class_1799.java:520) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1661.method_7381(class_1661.java:262) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1309.method_5773(class_1309.java:2346) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:466) ~[intermediary-server.jar:?]
12.08 22:13:12 [Server] INFO ... 9 more
12.08 22:13:12 [Disconnect] User WindowsLogic has disconnected, reason: Internal server error
12.08 22:13:12 [Server] Server thread/INFO WindowsLogic left the game
12.08 22:13:12 [Server] Server thread/INFO Disconnecting client WindowsLogic`

**Comment by loleq2105** [comment]
That's a critical issue if I've ever seen one! Working on it right now.

**Comment by windowslogic** [comment]
Thank you 👍

**Comment by loleq2105** [comment]
got networking figured out, only a matter of time (~16h, doing the rest 2moro) before the fixed version is dropped now. many thanks for your report :)

**Comment by loleq2105** [comment]
Alright, let me know if this release fixes your issue: https://www.curseforge.com/minecraft/mc-mods/gearreborn/files/3427016
By the way, rest assured, the NVG causes no player data corruption - it's just how my sloppy code... worked
